### ISSUE TITLE
Map of Byte Array to Charset or CharsetName

### ISSUE THREAD

**Issue by dwilkie** [twitter/cloudhopper-commons#7]
I'm trying to decode a MO message using `CharsetUtil.decode` but I don't know the `dataCoding` in advance. I can't seem to find a mapping between the `dataCoding` byte to the `Charset` or `CharsetName`

```java
      DeliverSm mo = (DeliverSm) pduRequest;
      byte dataCoding = mo.getDataCoding();
      byte[] shortMessage = mo.getShortMessage();
      // in the following line how can I get the CharsetName from dataCoding
      String messageText = CharsetUtil.decode(shortMessage, "UCS-2");
```

Am I missing something simple here?

**Comment by jjlauer** [comment]
You're confused because SMPP is unfortunately too lenient in my opinion on charsets.  The data coding value is defined in the GSM specs and also implemented here:

https://github.com/twitter/cloudhopper-commons/blob/master/ch-commons-gsm/src/main/java/com/cloudhopper/commons/gsm/DataCoding.java

There are defined charsets which make sense -- but they did leave a spot open called "default" charset.  You actually need to ask the SMSC what charset they use and "config" it on the bind.  We've also found, however, that even if the SMSC sets it to something like GSM, that may not be true.  Most times a carrier doesn't even really know what charset is used and you just need to test it out.  We usually ask the carrier to send an @ symbol, euro symbol, dollar symbol and just deduce the charset they use.  Trust but verify.

**Comment by jjlauer** [comment]
One more thing -- we've also found submits and delivers may or may not use the same default charset as well.  I wish the SMPP specs were more strict, but it is what it is.

**Comment by dwilkie** [comment]
@jjlauer thanks for your help here.

I just captured some packets from the SMSC we're connecting to and confirmed that they are, in-fact changing the DataCoding based off the message content.

I need to also confirm if they are sending in other charsets as well, e.g. LATIN 1 but I guess that if this is the case I'll need to trust the `DataCoding` that they send and dynamically decode it using the appropriate Charset.

Would you accept a PR if I put a map in CharSetUtils from the DataCoding byte to the CharSet for dynamic decoding?

I had a look through https://github.com/twitter/cloudhopper-commons/blob/master/ch-commons-gsm/src/main/java/com/cloudhopper/commons/gsm/DataCoding.java and I can see how I can make a new `DataCoding` instance from the `DataCoding` byte but it doesn't look like I can get the `Charset` from there so I can call `CharsetUtil.decode` with the correct Charset.

See attached files for reference.

![2015-02-23_rename_ext_to_cap](https://cloud.githubusercontent.com/assets/127583/6322577/ed56293e-bb49-11e4-94df-e78c15685e5c.png)
![2015-02-22_ucs2_deliver_sm](https://cloud.githubusercontent.com/assets/127583/6322578/ed583738-bb49-11e4-9fa7-9672776c887b.png)
![2015-02-22_default_alphabet_deliver_sm](https://cloud.githubusercontent.com/assets/127583/6322579/ed5c8f22-bb49-11e4-9158-b8871f0c6365.png)
